name: Test build on tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0.0
          args: install
      - name: Run build
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0.0
          args: build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
